name: macOS CI

on: [push, pull_request]

env:
  TESTS_REDUCED_KEYLENGTHS: yes
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_COMPRESS: true
  CCACHE_MAXSIZE: 100M
  CCACHE_LOGFILE: ${{ github.workspace }}/ccache.log
  OS_NAME: macos

jobs:
  macos:
    runs-on: macos-latest
    env:
      TEST: macos
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/Library/Caches/ccache
          key: ccache-${{ runner.os }}-${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ github.ref }}:
            ccache-${{ runner.os }}-
      - run: |
          brew install ccache
          echo "PATH=$(brew --prefix)/opt/ccache/libexec:$PATH" >> $GITHUB_ENV
          ccache -z
      - uses: ./.github/actions/default
      - run: ccache -s
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Logs ${{ github.job }}
          path: config.log
          retention-days: 5
