name: Windows CI

on: [push, pull_request]

env:
  TESTS_REDUCED_KEYLENGTHS: yes
  CCACHE_COMPRESS: true
  CCACHE_MAXSIZE: 200M
  # since the compilers are newly installed every time, we have to use this to
  # avoid cache misses
  CCACHE_COMPILERCHECK: content
  MONOLITHIC: yes

jobs:
  # cross-compile:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       test: [ win64, win32 ]
  #   env:
  #     CCACHE_BASEDIR: ${{ github.workspace }}
  #     OS_NAME: linux
  #     TEST: ${{ matrix.test }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/cache@v2
  #       with:
  #         path: ~/.ccache
  #         key: ccache-${{ runner.os }}-${{ matrix.test }}-${{ github.ref }}:${{ github.sha }}
  #         restore-keys: |
  #           ccache-${{ runner.os }}-${{ matrix.test }}-${{ github.ref }}:
  #           ccache-${{ runner.os }}-${{ matrix.test }}-
  #     - run: |
  #         sudo apt-get install -qq ccache
  #         echo "PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV
  #         ccache -z
  #     - uses: ./.github/actions/default
  #     - run: ccache -s
  #     - if: ${{ failure() }}
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: Logs ${{ github.job }}
  #         path: config.log
  #         retention-days: 5

  native:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - msystem: MINGW64
            test: win64
          - msystem: MINGW32
            test: win32
    env:
      OS_NAME: windows
      TEST: ${{ matrix.test }}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
      - run: git config --global core.autocrlf input
        shell: bash
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ccache-${{ runner.os }}-${{ matrix.test }}-${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ matrix.test }}-${{ github.ref }}:
            ccache-${{ runner.os }}-${{ matrix.test }}-
      - run: |
          ./scripts/test.sh deps
          case "$TEST" in
          win64)
            pacman --noconfirm -S --needed mingw-w64-x86_64-ccache
            echo "PATH=/mingw64/lib/ccache/bin:$PATH" >> $GITHUB_ENV
            ;;
          win32)
            pacman --noconfirm -S --needed mingw-w64-i686-ccache
            echo "PATH=/mingw32/lib/ccache/bin:$PATH" >> $GITHUB_ENV
            ;;
          esac
          # $GITHUB_WORKSPACE is a Windows path that ccache doesn't like
          echo "CCACHE_BASEDIR=$(pwd)" >> $GITHUB_ENV
          ccache -z
          ccache -s
        shell: msys2 {0}
      - run: ./scripts/test.sh
        shell: msys2 {0}
      - run: ccache -s
        shell: msys2 {0}
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Logs ${{ github.job }}
          path: config.log
          retention-days: 5
